server:
  port: 9999
  undertow:
      accesslog:
        enabled: true
        dir: logs/access
        rotate: true
      worker-threads: 10
      buffer-size: 1024
      direct-buffers: true
      max-http-post-size: 1024

spring:
  application:
    name: album
  datasource:
    url: jdbc:mysql://localhost:3306/photo_album?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 3
    min-idle: 5
    max-active: 10
    max-wait: 10000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
  redis:
    host: localhost
    password:
    port: 6379
    timeout: 3000ms
    jedis:
      pool:
        max-idle: 8
        min-idle: 1
        max-active: 8
        max-wait: -1ms

mybatis:
  mapper-locations: classpath:/mapper/*.xml

system:
  config:
    server-id: 1
    upload-file-path: D:/upload/other
    upload-photo-path: D:/upload/photo
    upload-buffer-size: 1024
    download-file-path: /file/download
    download-photo-path: /photo/download
    validate-cd-time-length: 60
    validate-time-length: 180
    token-secret: my_token
    token-valid-time-length: 3

